# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ecd7793afe0d4b48c0ac5d811a02d23a4d7e494827ab27cf2c4b961c1d7db4421171dd7f4436dbacde604df7998d7025f8b20c13fe50d5c1505d537d5140988

test:
  secret_key_base: c2b4d57681771dbf1b3f7a8d3a5e1cbea23da518e61b5e2374054ed142a13b736695813d9c076b110ba968d21c7e7d24552d0c827d0f12d12ac91fe3c82dae63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
